using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Unity.Collections;
using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using UnityEngine;

namespace C6Lab
{
    [Serializable]
    internal sealed class LabNetworkPacket
    {
        public int protocol = 1;
        public string type;
        public string sessionId;
        public ulong[] seats;
        public LabSnapshot snapshot;
        public long requestId;
        public string firstId;
        public string secondId;
        public bool right;
        public float x;
        public float y;
        public float vx;
        public float vy;
        public float vz;
        public float z;
        public float wx;
        public float wy;
        public float wz;
        public string reason;
        public ulong owner;
    }

    /// <summary>
    /// A deliberately small, direct-IP, three-peer experiment. The host alone owns LabModel.
    /// Only owner motion is simulated locally; requests and damage are accepted by the host.
    /// </summary>
    public sealed class LabNetwork : MonoBehaviour
    {
        private const string MessageName = "C6Lab.Packet.1";
        // 3D board physics changes motion semantics even though snapshots remain planar.
        // Reject old clients rather than mixing two simulations in a single room.
        private const ushort LabProtocolVersion = 5603;
        private static readonly byte[] LabConnectionToken = Encoding.ASCII.GetBytes("C6PhysicsLab/3");
        private const int MaximumPacketBytes = 32768;
        private static readonly UTF8Encoding Utf8 = new UTF8Encoding(false, true);
        public LabConfig config;
        public LabOrbBoard board;
        public LabTarget target;
        public Collider battleFloor;
        public Transform projectileRoot;
        public NetworkManager manager;
        public UnityTransport transport;
        public ushort port = 7777;
        public string hostAddress = "127.0.0.1";

        private readonly List<ulong> order = new List<ulong>(3);
        private readonly HashSet<string> visibleOrbIds = new HashSet<string>();
        private LabModel model;
        private double nextSnapshotAt;
        private double nextMotionAt;
        private long requestSequence;
        private bool handlerRegistered;
        private bool autoStart;
        private bool autoGenerate;
        private bool autoTransfer;
        private bool developerSolo;
        private string autoGeneratedSession;
        private string autoTransferredSession;
        private bool stopping;
        private bool stopAfterDisconnect;
        private string sessionId;
        private LabSnapshot latest;

        public event Action Changed;
        public string Status { get; private set; } = "Choose HOST or JOIN.";
        public string Notice { get; private set; } = string.Empty;
        public string LastShotReport { get; private set; } = string.Empty;
        public int ParticipantCount => order.Count;
        public bool IsHost => manager != null && manager.IsHost;
        public bool IsDeveloperSolo => developerSolo;
        public bool DeveloperBuildAvailable => Application.isEditor || Debug.isDebugBuild;
        public bool IsConnected => manager != null && manager.IsListening && (manager.IsHost || manager.IsConnectedClient);
        public ulong LocalPlayerId => IsConnected ? manager.LocalClientId : ulong.MaxValue;
        public LabSnapshot Snapshot => latest;
        public bool CanStartBattle => IsHost && order.Count == 3 && (latest == null || latest.phase != LabPhase.Playing);

        private void Awake()
        {
            if (manager == null) manager = GetComponent<NetworkManager>();
            if (transport == null) transport = GetComponent<UnityTransport>();
            if (board != null)
            {
                board.EdgeCrossed += OnEdgeCrossed;
                board.CombineRequested += OnCombineRequested;
                board.ThrowRequested += OnThrowRequested;
            }
            if (manager != null)
            {
                manager.OnClientConnectedCallback += OnConnected;
                manager.OnClientDisconnectCallback += OnDisconnected;
                manager.OnTransportFailure += OnTransportFailure;
            }
        }

        private void Start()
        {
            var args = Environment.GetCommandLineArgs();
            for (int i = 0; i < args.Length; i++)
            {
                if (args[i] == "--lab-port" && i + 1 < args.Length && ushort.TryParse(args[i + 1], out var chosenPort)) port = chosenPort;
                else if (args[i] == "--lab-join" && i + 1 < args.Length) hostAddress = args[i + 1];
                else if (args[i] == "--lab-auto-start") autoStart = true;
                else if (args[i] == "--lab-auto-generate") autoGenerate = true;
                else if (args[i] == "--lab-auto-transfer") autoTransfer = true;
            }
            if (Array.IndexOf(args, "--lab-host") >= 0) Host();
            else if (Array.IndexOf(args, "--lab-join") >= 0) Join(hostAddress);
        }

        public void Host()
        {
            if (IsConnected || manager == null || transport == null || config == null) return;
            ResetLocal();
            ConfigureManager();
            transport.SetConnectionData("127.0.0.1", port, "0.0.0.0");
            if (!manager.StartHost()) { SetStatus("Host failed: check port and network."); return; }
            RegisterHandler();
            if (!order.Contains(manager.LocalClientId)) order.Add(manager.LocalClientId);
            SetStatus("HOST listening on port " + port + "; waiting for 2 peers.");
            Debug.Log("C6_LAB_HOST port=" + port + " protocol=" + LabProtocolVersion);
            BroadcastLobby();
        }

        public void Join(string address)
        {
            if (IsConnected || manager == null || transport == null || config == null) return;
            if (string.IsNullOrWhiteSpace(address)) { SetStatus("Enter the Host IP address."); return; }
            hostAddress = address.Trim();
            ResetLocal();
            ConfigureManager();
            try { transport.SetConnectionData(hostAddress, port); }
            catch (Exception e) { SetStatus("Invalid Host address: " + e.GetType().Name); return; }
            if (!manager.StartClient()) { SetStatus("Connection could not start."); return; }
            RegisterHandler();
            SetStatus("Connecting to " + hostAddress + ":" + port + "...");
            Debug.Log("C6_LAB_JOIN address=" + hostAddress + " port=" + port);
        }

        public void Stop()
        {
            if (stopping) return;
            stopping = true;
            if (handlerRegistered && manager != null && manager.CustomMessagingManager != null)
            {
                manager.CustomMessagingManager.UnregisterNamedMessageHandler(MessageName);
                handlerRegistered = false;
            }
            if (manager != null && manager.IsListening && !manager.ShutdownInProgress) manager.Shutdown();
            ResetLocal();
            SetStatus("Disconnected. Choose HOST or JOIN.");
            stopping = false;
        }

        public void StartBattle()
        {
            if (!CanStartBattle) { SetNotice("Exactly 3 connected players are required."); return; }
            sessionId = Guid.NewGuid().ToString("N");
            model = new LabModel();
            model.Begin(sessionId, order.ToArray(), Time.realtimeSinceStartupAsDouble, config);
            SetNotice(string.Empty);
            PublishSnapshot(true);
            SetStatus("PLAYING: 3 / 3");
            Debug.Log("C6_LAB_START session=" + sessionId + " seats=" + string.Join(",", order));
        }

        /// <summary>Start a one-player Host session only in the Editor or a Development Build.</summary>
        public bool StartDeveloperSolo()
        {
            if (!DeveloperBuildAvailable)
            {
                SetNotice("Developer Solo requires a Development Build.");
                return false;
            }
            if (IsConnected)
            {
                SetNotice("Leave the current session before starting Developer Solo.");
                return false;
            }
            Host();
            if (!IsHost || order.Count != 1) return false;
            developerSolo = true;
            BeginDeveloperSoloRound();
            return true;
        }

        /// <summary>Apply new runtime tuning by starting a fresh one-player round.</summary>
        public bool RestartDeveloperSolo()
        {
            if (!DeveloperBuildAvailable || !developerSolo || !IsHost || order.Count != 1 || config == null)
            {
                SetNotice("Start Developer Solo before applying a new round.");
                return false;
            }
            ClearProjectiles();
            if (board != null) board.Clear();
            visibleOrbIds.Clear();
            latest = null;
            BeginDeveloperSoloRound();
            return true;
        }

        private void BeginDeveloperSoloRound()
        {
            LastShotReport = string.Empty;
            sessionId = Guid.NewGuid().ToString("N");
            model = new LabModel();
            model.BeginSolo(sessionId, LocalPlayerId, Time.realtimeSinceStartupAsDouble, config);
            SetNotice(string.Empty);
            PublishSnapshot(true);
            SetStatus("DEVELOPER SOLO: 1 / 1");
            Debug.Log("C6_LAB_SOLO_START session=" + sessionId + " player=" + LocalPlayerId);
        }

        public void Generate()
        {
            if (!IsConnected || latest == null || latest.phase != LabPhase.Playing) return;
            Request(new LabNetworkPacket { type = "generate", requestId = ++requestSequence });
        }

        private void Update()
        {
            if (stopAfterDisconnect) { stopAfterDisconnect = false; Stop(); return; }
            double now = Time.realtimeSinceStartupAsDouble;
            if (IsHost && model != null)
            {
                model.Tick(now);
                if (now >= nextSnapshotAt) PublishSnapshot(false);
            }
            // Command-line smoke mode is intentionally separate from ordinary UI play.
            if (IsConnected && latest != null && latest.phase == LabPhase.Playing)
            {
                if (autoGenerate && autoGeneratedSession != latest.sessionId)
                {
                    autoGeneratedSession = latest.sessionId;
                    Generate();
                }
                if (IsHost && autoTransfer && autoTransferredSession != latest.sessionId)
                {
                    LabOrbState candidate = null;
                    foreach (var orb in latest.orbs ?? Array.Empty<LabOrbState>())
                        if (orb.owner == LocalPlayerId && !orb.inFlight) { candidate = orb; break; }
                    if (candidate != null)
                    {
                        autoTransferredSession = latest.sessionId;
                        Request(new LabNetworkPacket { type = "motion", firstId = candidate.id, x = 1f, y = .5f, vx = 3f, vy = 0f });
                        Request(new LabNetworkPacket { type = "transfer", firstId = candidate.id, requestId = ++requestSequence,
                            right = true, y = .5f, vx = 3f, vy = 0f });
                        Debug.Log("C6_LAB_SMOKE_EDGE orb=" + candidate.id);
                    }
                }
            }
            if (IsConnected && board != null && latest != null && latest.phase == LabPhase.Playing && now >= nextMotionAt)
            {
                nextMotionAt = now + 0.1;
                foreach (var orb in latest.orbs ?? Array.Empty<LabOrbState>())
                {
                    if (orb.owner != LocalPlayerId || orb.inFlight) continue;
                    if (board.TryGetMotion(orb.id, out var position, out var velocity))
                        Request(new LabNetworkPacket { type = "motion", firstId = orb.id, x = position.x, y = position.y, vx = velocity.x, vy = velocity.y });
                }
            }
        }

        private void ConfigureManager()
        {
            manager.NetworkConfig = new NetworkConfig
            {
                NetworkTransport = transport,
                ProtocolVersion = LabProtocolVersion,
                ConnectionData = (byte[])LabConnectionToken.Clone(),
                EnableSceneManagement = false,
                ConnectionApproval = true,
                PlayerPrefab = null,
                ClientConnectionBufferTimeout = 10
            };
            manager.ConnectionApprovalCallback = Approve;
        }

        private void Approve(NetworkManager.ConnectionApprovalRequest request, NetworkManager.ConnectionApprovalResponse response)
        {
            bool allowed = manager.IsHost && order.Count < 3 && model == null
                && request.Payload != null && request.Payload.SequenceEqual(LabConnectionToken);
            response.Approved = allowed;
            response.CreatePlayerObject = false;
            response.Pending = false;
            response.Reason = allowed ? string.Empty : "Lab version mismatch, room full, or battle started.";
        }

        private void RegisterHandler()
        {
            if (handlerRegistered || manager.CustomMessagingManager == null) return;
            manager.CustomMessagingManager.RegisterNamedMessageHandler(MessageName, Receive);
            handlerRegistered = true;
        }

        private void OnConnected(ulong id)
        {
            if (stopping || manager == null) return;
            RegisterHandler();
            if (manager.IsHost)
            {
                if (!order.Contains(id) && order.Count < 3) order.Add(id);
                Debug.Log("C6_LAB_PEER_JOIN id=" + id + " participants=" + order.Count);
                BroadcastLobby();
                if (autoStart && order.Count == 3) StartBattle();
            }
            else if (id == manager.LocalClientId)
            {
                SetStatus("Connected; waiting for 3 players.");
                Debug.Log("C6_LAB_CONNECTED local=" + id);
            }
        }

        private void OnDisconnected(ulong id)
        {
            if (stopping) return;
            if (manager != null && manager.IsHost)
            {
                if (!order.Remove(id))
                {
                    Debug.Log("C6_LAB_JOIN_REJECTED id=" + id);
                    return;
                }
                Debug.LogWarning("C6_LAB_PEER_LEFT id=" + id);
                if (model != null) { model = null; latest = null; if (board != null) board.Clear(); }
                BroadcastLobby();
                SetStatus("A player left. Connect exactly 3 before starting.");
            }
            else
            {
                stopAfterDisconnect = true;
                string reason = manager == null ? string.Empty : manager.DisconnectReason;
                SetStatus(string.IsNullOrEmpty(reason) ? "Connection ended. Rejoin the Host." : "Join failed: " + reason);
                Debug.LogWarning("C6_LAB_DISCONNECTED reason=" + reason);
            }
        }

        private void OnTransportFailure()
        {
            SetStatus("Network transport failed. Check IP, port, and same network.");
            Debug.LogWarning("C6_LAB_TRANSPORT_FAILURE");
        }

        private void BroadcastLobby()
        {
            if (!IsHost) return;
            var packet = new LabNetworkPacket { type = "lobby", seats = order.ToArray() };
            foreach (ulong id in order) if (id != manager.LocalClientId) Send(id, packet);
            SetStatus("LOBBY: " + order.Count + " / 3");
            Changed?.Invoke();
        }

        private void PublishSnapshot(bool immediate)
        {
            if (!IsHost || model == null) return;
            double now = Time.realtimeSinceStartupAsDouble;
            latest = model.Snapshot(now);
            nextSnapshotAt = now + 0.1;
            SyncBoard();
            var packet = new LabNetworkPacket { type = "snapshot", sessionId = sessionId, snapshot = latest };
            foreach (ulong id in order) if (id != manager.LocalClientId) Send(id, packet);
            if (immediate) Debug.Log("C6_LAB_STATE phase=" + latest.phase + " hp=" + latest.hp + " remaining=" + latest.remaining.ToString("F1"));
            Changed?.Invoke();
        }

        private void Request(LabNetworkPacket packet)
        {
            packet.sessionId = sessionId;
            if (IsHost) HandleRequest(LocalPlayerId, packet);
            else Send(NetworkManager.ServerClientId, packet);
        }

        private void HandleRequest(ulong sender, LabNetworkPacket packet)
        {
            if (!IsHost || model == null || packet == null || !order.Contains(sender)) return;
            double now = Time.realtimeSinceStartupAsDouble;
            bool accepted = false;
            string reason = "Rejected";
            if (packet.sessionId != sessionId) return;
            LabOrbState result = null;
            string uniqueRequestId = sender + ":" + packet.requestId;
            switch (packet.type)
            {
                case "generate":
                    accepted = model.TryGenerate(sender, uniqueRequestId, now, out result, out reason);
                    break;
                case "combine":
                    accepted = model.TryCombine(sender, packet.firstId, packet.secondId, uniqueRequestId, now, out result, out reason);
                    break;
                case "transfer":
                    accepted = model.TryTransfer(sender, packet.firstId, packet.right, packet.y, new Vector2(packet.vx, packet.vy), uniqueRequestId, now, out result, out reason);
                    break;
                case "launch":
                    Vector2 swipe = new Vector2(packet.vx, packet.vy);
                    if (target == null || target.Hitbox == null || battleFloor == null)
                    {
                        reason = "Battle target or floor is unavailable.";
                        break;
                    }
                    if (!Finite(packet.x) || packet.x < 0f || packet.x > 1f
                        || !LabThrowMath.IsThrowGesture(swipe, packet.y, config))
                    {
                        reason = "Swipe the Combined orb upward to throw.";
                        break;
                    }
                    accepted = model.TryLaunch(sender, packet.firstId, uniqueRequestId, now, out result, out reason);
                    if (accepted) SpawnHostProjectile(result, swipe, packet.x);
                    break;
                case "motion":
                    if (Finite(packet.x) && Finite(packet.y) && Finite(packet.vx) && Finite(packet.vy))
                        accepted = model.TryUpdateMotion(sender, packet.firstId, new Vector2(packet.x, packet.y), new Vector2(packet.vx, packet.vy), now);
                    // Frequent or late motion samples are best-effort; never unlock an orb from them.
                    return;
            }
            if (accepted)
            {
                Debug.Log("C6_LAB_ACTION type=" + packet.type + " sender=" + sender + " orb=" + (result == null ? "" : result.id)
                    + (result == null ? "" : " owner=" + result.owner + " vx=" + result.vx.ToString("F2")));
                PublishSnapshot(true);
            }
            else if (sender == LocalPlayerId) RejectLocally(packet.firstId, reason);
            else Send(sender, new LabNetworkPacket { type = "reject", firstId = packet.firstId, reason = reason });
        }

        private void SpawnHostProjectile(LabOrbState orb, Vector2 releaseVelocity, float releaseX01)
        {
            if (orb == null || target == null || config == null) return;
            int seat = latest != null && latest.players != null ? Array.Find(latest.players, p => p.id == orb.owner)?.seat ?? order.IndexOf(orb.owner) : order.IndexOf(orb.owner);
            Vector3 targetCenter = target.transform.position;
            Vector3 seatAnchor = LabThrowMath.SeatPosition(seat, 3, targetCenter,
                config.ThrowOriginRadius, config.ThrowOriginHeightOffset);
            Vector3 launchPosition = LabThrowMath.LaunchPosition(seat, 3, targetCenter, releaseX01, config);
            Vector3 velocity = LabThrowMath.LaunchVelocity(releaseVelocity, seatAnchor, targetCenter, config);
            var projectile = LabProjectile.Create(launchPosition, config, projectileRoot);
            projectile.name = "Projectile " + orb.id;
            projectile.SetMissSurface(battleFloor);
            projectile.Launch(orb.id, orb.owner, velocity, config, target, OnProjectileResolved);
            var notice = new LabNetworkPacket { type = "projectile", firstId = orb.id, owner = orb.owner, x = launchPosition.x, y = launchPosition.y, z = launchPosition.z, wx = velocity.x, wy = velocity.y, wz = velocity.z };
            foreach (ulong id in order) if (id != LocalPlayerId) Send(id, notice);
            Debug.Log("C6_LAB_THROW orb=" + orb.id + " seat=" + seat
                + " swipe=" + releaseVelocity + " launch=" + velocity
                + " exponent=" + config.ThrowPowerExponent.ToString("F2", CultureInfo.InvariantCulture)
                + " loft=" + config.ThrowLoftOffsetDegrees.ToString("F1", CultureInfo.InvariantCulture)
                + " damping=" + config.ThrowAirDamping.ToString("F2", CultureInfo.InvariantCulture));
        }

        private void OnProjectileResolved(LabProjectileResult result)
        {
            if (!IsHost || model == null) return;
            double now = Time.realtimeSinceStartupAsDouble;
            if (result.Hit) model.ConfirmHit(result.ProjectileId, now);
            else model.ConfirmMiss(result.ProjectileId, now);
            LastShotReport = string.Format(CultureInfo.InvariantCulture,
                "SHOT {0} | {1:F2}s | peak +{2:F2}m | range {3:F2}m",
                result.Hit ? "HIT" : "MISS", result.FlightSeconds,
                result.PeakRise, result.HorizontalDistance);
            Debug.Log("C6_LAB_PROJECTILE id=" + result.ProjectileId + " hit=" + result.Hit
                + " flight=" + result.FlightSeconds.ToString("F2", CultureInfo.InvariantCulture)
                + " peak=" + result.PeakRise.ToString("F2", CultureInfo.InvariantCulture)
                + " range=" + result.HorizontalDistance.ToString("F2", CultureInfo.InvariantCulture)
                + " contact=" + result.HitPoint);
            if (developerSolo) SetNotice(LastShotReport);
            PublishSnapshot(true);
        }

        private void SyncBoard()
        {
            if (board == null || latest == null) return;
            var current = new HashSet<string>();
            foreach (var orb in latest.orbs ?? Array.Empty<LabOrbState>())
            {
                if (orb.owner != LocalPlayerId || orb.inFlight) continue;
                current.Add(orb.id);
                bool showRise = orb.origin == LabOrbOrigin.Generated && orb.originOwner == LocalPlayerId
                    && orb.kind != LabOrbKind.Combined;
                board.UpsertOrb(orb.id, orb.kind, new Vector2(orb.x, orb.y),
                    new Vector2(orb.vx, orb.vy), true, showRise);
            }
            foreach (string id in visibleOrbIds) if (!current.Contains(id)) board.RemoveOrb(id);
            visibleOrbIds.Clear();
            foreach (string id in current) visibleOrbIds.Add(id);
            board.SetInteractionEnabled(latest.phase == LabPhase.Playing);
        }

        private void OnEdgeCrossed(LabOrbEdgeCrossing edge)
        {
            if (latest == null || latest.phase != LabPhase.Playing) return;
            if (developerSolo)
            {
                // The single player has no neighbor. Restore the stopped edge orb immediately.
                board.RejectEdge(edge.OrbId);
                return;
            }
            board.SetOrbLocked(edge.OrbId, true);
            // The Host must receive the boundary sample before the ownership request.
            Request(new LabNetworkPacket { type = "motion", firstId = edge.OrbId, x = edge.ToRight ? 1f : 0f, y = edge.Height01, vx = edge.VelocityInBoardWidthsPerSecond.x, vy = edge.VelocityInBoardWidthsPerSecond.y });
            Request(new LabNetworkPacket { type = "transfer", requestId = ++requestSequence, firstId = edge.OrbId, right = edge.ToRight, y = edge.Height01, vx = edge.VelocityInBoardWidthsPerSecond.x, vy = edge.VelocityInBoardWidthsPerSecond.y });
        }

        private void OnCombineRequested(string firstId, string secondId, Vector2 center)
        {
            if (latest == null || latest.phase != LabPhase.Playing) return;
            Request(new LabNetworkPacket { type = "combine", requestId = ++requestSequence, firstId = firstId, secondId = secondId, x = center.x, y = center.y });
        }

        private void OnThrowRequested(LabOrbThrowGesture gesture)
        {
            if (latest == null || latest.phase != LabPhase.Playing) return;
            board.SetOrbLocked(gesture.OrbId, true);
            Request(new LabNetworkPacket { type = "launch", requestId = ++requestSequence,
                firstId = gesture.OrbId, x = gesture.ReleaseX01,
                y = gesture.DistanceInBoardWidths, vx = gesture.Velocity.x, vy = gesture.Velocity.y });
        }

        private void Receive(ulong sender, FastBufferReader reader)
        {
            if (!TryRead(reader, out var packet)) return;
            if (IsHost)
            {
                if (sender == LocalPlayerId || !order.Contains(sender)) return;
                HandleRequest(sender, packet);
                return;
            }
            if (sender != NetworkManager.ServerClientId) return;
            switch (packet.type)
            {
                case "lobby":
                    order.Clear();
                    latest = null;
                    visibleOrbIds.Clear();
                    if (board != null) board.Clear();
                    if (packet.seats != null) order.AddRange(packet.seats);
                    SetStatus("LOBBY: " + order.Count + " / 3");
                    Debug.Log("C6_LAB_LOBBY participants=" + order.Count + " seats=" + string.Join(",", order));
                    break;
                case "snapshot":
                    if (packet.snapshot == null || packet.snapshot.players == null || packet.snapshot.players.Length != 3) return;
                    if (latest != null && latest.sessionId == packet.snapshot.sessionId && latest.round > packet.snapshot.round) return;
                    bool logTransition = latest == null || latest.sessionId != packet.snapshot.sessionId || latest.phase != packet.snapshot.phase;
                    sessionId = packet.snapshot.sessionId;
                    latest = packet.snapshot;
                    SyncBoard();
                    if (logTransition && latest.phase == LabPhase.Playing) SetNotice(string.Empty);
                    SetStatus(latest.phase + ": 3 / 3");
                    if (logTransition) Debug.Log("C6_LAB_SNAPSHOT phase=" + latest.phase + " hp=" + latest.hp + " remaining=" + latest.remaining.ToString("F1") + " orbs=" + (latest.orbs?.Length ?? 0));
                    break;
                case "reject":
                    RejectLocally(packet.firstId, packet.reason);
                    break;
                case "projectile":
                    if (target != null && config != null && Finite(packet.x) && Finite(packet.y)
                        && Finite(packet.z) && Finite(packet.wx) && Finite(packet.wy) && Finite(packet.wz))
                    {
                        Vector3 position = new Vector3(packet.x, packet.y, packet.z);
                        Vector3 velocity = new Vector3(packet.wx, packet.wy, packet.wz);
                        LabProjectile visual = LabProjectile.Create(position, config, projectileRoot);
                        visual.SetMissSurface(battleFloor);
                        visual.LaunchVisual(velocity, config, target);
                    }
                    break;
            }
        }

        private void RejectLocally(string orbId, string reason)
        {
            if (!string.IsNullOrEmpty(orbId) && board != null) board.RejectEdge(orbId);
            SetNotice(reason ?? "Request rejected.");
            Debug.LogWarning("C6_LAB_REJECT orb=" + orbId + " reason=" + reason);
        }

        private bool Send(ulong receiver, LabNetworkPacket packet)
        {
            if (manager == null || !manager.IsListening || manager.ShutdownInProgress || manager.CustomMessagingManager == null) return false;
            try
            {
                byte[] bytes = Utf8.GetBytes(JsonUtility.ToJson(packet));
                if (bytes.Length < 1 || bytes.Length > MaximumPacketBytes - 8) return false;
                using (var writer = new FastBufferWriter(bytes.Length + 8, Allocator.Temp))
                {
                    writer.WriteValueSafe(packet.protocol);
                    writer.WriteValueSafe(bytes.Length);
                    writer.WriteBytesSafe(bytes);
                    manager.CustomMessagingManager.SendNamedMessage(MessageName, receiver, writer, NetworkDelivery.ReliableFragmentedSequenced);
                }
                return true;
            }
            catch (Exception e)
            {
                Debug.LogWarning("C6_LAB_SEND_FAILED " + e.GetType().Name);
                return false;
            }
        }

        private static bool TryRead(FastBufferReader reader, out LabNetworkPacket packet)
        {
            packet = null;
            int left = reader.Length - reader.Position;
            if (left < 9 || left > MaximumPacketBytes || !reader.TryBeginRead(left)) return false;
            try
            {
                reader.ReadValueSafe(out int version);
                reader.ReadValueSafe(out int count);
                if (version != 1 || count < 2 || count != reader.Length - reader.Position) return false;
                var bytes = new byte[count];
                reader.ReadBytesSafe(ref bytes, count);
                packet = JsonUtility.FromJson<LabNetworkPacket>(Utf8.GetString(bytes));
                return packet != null && packet.protocol == 1 && !string.IsNullOrEmpty(packet.type);
            }
            catch (Exception) { return false; }
        }

        private static bool Finite(float value) => !float.IsNaN(value) && !float.IsInfinity(value);

        private void ResetLocal()
        {
            ClearProjectiles();
            order.Clear();
            visibleOrbIds.Clear();
            model = null;
            developerSolo = false;
            latest = null;
            sessionId = null;
            LastShotReport = string.Empty;
            requestSequence = 0;
            if (board != null) board.Clear();
            Changed?.Invoke();
        }

        private void ClearProjectiles()
        {
            if (projectileRoot == null) return;
            for (int i = 0; i < projectileRoot.childCount; i++)
            {
                GameObject projectile = projectileRoot.GetChild(i).gameObject;
                projectile.SetActive(false);
                Destroy(projectile);
            }
        }

        private void SetStatus(string status) { Status = status; Changed?.Invoke(); }
        private void SetNotice(string notice) { Notice = notice; Changed?.Invoke(); }

        private void OnDestroy()
        {
            if (board != null)
            {
                board.EdgeCrossed -= OnEdgeCrossed;
                board.CombineRequested -= OnCombineRequested;
                board.ThrowRequested -= OnThrowRequested;
            }
            if (manager != null)
            {
                manager.OnClientConnectedCallback -= OnConnected;
                manager.OnClientDisconnectCallback -= OnDisconnected;
                manager.OnTransportFailure -= OnTransportFailure;
            }
            Stop();
        }
    }
}
